# docker compose file for development useage
version: '3.8'
services:

  postgis:
    ports:
      - 5555:5432

  backend:
    build:
      args:
        SWEETHOME_PRODUCTION: "False"
    env_file:
      - docker/backend/.sweethome.env
      - docker/backend/.sweethome.dev.env
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
