# docker compose file for development with visual studio code
version: "3.8"
services:

  backend:
    # entrypoint: >
    #   /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678 /opt/sweethome/manage.py makemigrations accounts home"
    # entrypoint: >
    #   /bin/bash -c "python /opt/sweethome/manage.py graph_models -a -g -o models.png"
    # entrypoint: >
    #   /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678
    #   /opt/sweethome/manage.py squashmigrations registry 0002"
    # entrypoint: >
    #   /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678
    #   /opt/sweethome/manage.py migrate"
    # entrypoint: >
    #   /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678
    #   /opt/sweethome/manage.py loaddata test_users"
    # entrypoint: >
    #   /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678
    #   /opt/sweethome/manage.py dumpdata --natural-foreign --natural-primary registry
    #   > fixture.json"
    command: >
      /bin/bash -c "python -u -m debugpy --listen 0.0.0.0:5678 /opt/sweethome/manage.py runserver 0.0.0.0:8001"

    ports:
      - "0.0.0.0:3001:5678"
