# docker compose file for productive useage
version: '3.8'
services:
  postgis:
    image: postgis/postgis:14-3.1-alpine
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    networks:
      - sweethome-internal
    env_file:
      - ./docker/postgis/.db.env

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
      args:
        SWEETHOME_PRODUCTION: "True"
    tty: true # To support colorized log output.
    entrypoint: /opt/sweethome/.bash_scripts/entrypoint.sh
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8001"

    hostname: "sweethome-backend"
    volumes:
      - type: bind
        source: ./backend
        target: /opt/sweethome
      - type: volume
        source: sweethome-static
        target: /var/www/sweethome/static
      - type: volume
        source: sweethome-media
        target: /var/sweethome/media
      - type: volume
        source: sweethome-log
        target: /var/log/sweethome
    networks:
      - sweethome-internal
    env_file:
      - docker/backend/.sweethome.env
    depends_on:
      - postgis

volumes:
  sweethome-static: null
  sweethome-media: null
  sweethome-log: null
  db-data: null

networks:
  sweethome-internal: null
